### PR TITLE
Favicon linked to ACM logo

### PR DESCRIPTION
**Pull request by achen409**
image

### CODE REVIEW

**Review by shahdivyank — CHANGES_REQUESTED** [review]
Implement through public folder

**Comment by achen409** [comment]
image
implemented through public folder now.

**Comment by shahdivyank** [comment]
> image
> implemented through public folder now.

Put a favicon file in the public folder and you are good to go. You do not need to modify any of the files

**Comment by achen409** [comment]
I think my change made it so that _document.js accesses acm-ucr-logo.webp from the public folder.

**Review by shahdivyank — APPROVED** [review]

**Pull request merged**
